version: '3'

services:
  nginx-node:
    build:
      context: .
      dockerfile: Dockerfile.node.nginx
    ports:
      - "12301:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    user: "setu:setu"
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "9000:9000"
    working_dir: /usr/share/nginx/html

